### ISSUE TITLE
Not working from North America

### ISSUE THREAD

**Issue by robitacs** [ddsol/speedtest.net#100]
After the successful fix earlier this week (https://github.com/ddsol/speedtest.net/issues/98) the service works properly everywhere (tested from Europe) except North America (US, Canada). 
Am I the only one affected?

**Comment by prabhuofficial** [comment]
Am also facing the similar issue it works from India and not for the US region

**Comment by ddsol** [comment]
I am running it from the US and it's working fine for me. Without more information I can't do anything about this, so I'm closing this issue.

**Comment by robitacs** [comment]
Well, it doesn't work for me.  @ddsol for your reference if this issue will spread across other regions. I found out that the servers only accept it with gzip now. 
This works for me: 
curl http://c.speedtest.net/speedtest-servers-static.php -H "accept-encoding: gzip" --compressed
Also once you get the zipped xml you need to unzip it. :)

**Comment by ddsol** [comment]
Should be fixed in 1.6.2, please let me know if it works.
