### ISSUE TITLE
It's closing without results/previously it finish.

### ISSUE THREAD

**Issue by sposmen** [ddsol/speedtest.net#105]
![image](https://user-images.githubusercontent.com/1591405/77642840-4da31900-6f2c-11ea-8f64-d3c8144ae094.png)

**Comment by marcelothebuilder** [comment]
I came here trying to find an answer for this same problem... Found out that running `speedtest-net  --accept-license` works

**Comment by sposmen** [comment]
> I came here trying to find an answer for this same problem... Found out that running `speedtest-net --accept-license` works

Thanks that solved the problem.
