### ISSUE TITLE
error module while running 1st time

### ISSUE THREAD

**Issue by fgroupindonesia** [ddsol/speedtest.net#107]
i think i missing something

when i run on the 1st time... it said:

```
Uncaught Error: Cannot find module 'C:\Users\asus\Documents\Projects\Javascript\NodeJS\ElectronTryMe\node_modules\lzma-native\binding-v4.0.6-electron-v8.1-win32-x64\lzma_native.node'
Require stack:
```

**Comment by ddsol** [comment]
You're using electron to run speedtest but you used node.js to install it. Since this module uses a compiled module this won't work because the module will be compiled for your version of node.js. I am not sure how to get it to work in electron but I'm sure the electron docs can help you out.
