### ISSUE TITLE
How would you recommend this is used

### ISSUE THREAD

**Issue by gate3** [ddsol/speedtest.net#110]
Hi, the wonderful solution here. Meets my requirements 100%. However I have some issues, I have been able to install and work with this on my server, using socketio as a layer to the client and all works well. But as expected, it uses my server's IP and also my servers internet speed. I have also tried making this a clientside module using browserify, I first encountered an issue with util.promisify which I solved by polyfilling and now another issue with fs.statSync not being a function. 

Who has been able to successfully deploy this package to work well with the client and how have you done so?

Server: Heroku
Environment: Nodejs, with Plain html, css and Js

**Comment by ddsol** [comment]
This module cannot work in the browser since it uses the official Speedtest command line client which cannot run in the browser.
