### ISSUE TITLE
Deployment needs some help

### ISSUE THREAD

**Issue by girishnair000** [ddsol/speedtest.net#111]
I can't find it work properly when deployed to server. 
It gives the information of server's ISP and not my local ISP from where I'm opening in the browser
By the way I used heroku
Any help highly appreciated

**Comment by ddsol** [comment]
It works fine when deployed to a server.
This package is not designed to make a copy of the speedtest.net website. It doesn't work in the browser. It's not for the browser. It will only work to test the internet speed of the system that the code runs on.

If this is not not what you want to do then this package is not for you.

**Comment by girishnair000** [comment]
I meant no disrespect.
It works fine on my local machine and when deployed on the server too it
worked.
But I didn't know it was not meant for browser and your reply clarified it
I always respect coders and their works
Thanks
