### ISSUE TITLE
What is accept license?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [ddsol/speedtest.net#135]
What is accept license?

Error: 
==============================================================================
You may only use this Speedtest software and information generated
from it for personal, non-commercial use, through a command line
interface on a personal computer. Your use of this software is subject
to the End User License Agreement, Terms of Use and Privacy Policy at
these URLs:
	https://www.speedtest.net/about/eula
	https://www.speedtest.net/about/terms
	https://www.speedtest.net/about/privacy
==============================================================================
To accept the message, pass the acceptLicense: true option

**Comment by ddsol** [comment]
It's simple. Follow the links and if you're okay with what you find the, pass `acceptLicense: true`.
