### ISSUE TITLE
How about an example or explanation of how the following, bandwidth: 3701179, bytes: 35468808, elapsed: 9703, related to each other?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [ddsol/speedtest.net#136]
How about an example or explanation of how the following, bandwidth: 3701179, bytes: 35468808, elapsed: 9703, related to each other?  The CLI does this but you just expose the raw results in NR.  How do you have NR, match what the CLI does?

Why not have NR data structure return results comparable the CLI?  Such as download, 31.64 Mbps, and upload 11.71 Mbps for example?

**Comment by adamk** [comment]
**Bandwidth** - Actual internet download speed in Bps (Bytes per second), from man speedtest:

`The human-readable format defaults to Mbps and any machine-readable formats (csv, tsv, json, jsonl, json-pretty) use bytes as the unit of measure with max precision.`

To get value in Mbps, as in following image you have to divide it by 125000:

`The bytes per second measurements can be transformed into the human-readable output format default unit of megabits (Mbps) by dividing the bytes per second value by 125,000.
`

**Bytes** - Volume of data used during the test (also in bytes)

**Elapsed** - Duration of testing download speed, in ms - how much time the testing took.
