### ISSUE TITLE
testserver data does not have same properties as data event

### ISSUE THREAD

**Issue by SamVerschueren** [ddsol/speedtest.net#14]
Hi

The `testserver` event returns an object with properties of the server that is being used for testing. The `data` event does also return those values, but with different property names.

Just to name a few:

testserver | data
------------ | -------------
host | url
location | name
distance | dist

I think it would be nice to make them both consistent and be sure both events have the same properties.

**Comment by ddsol** [comment]
That sounds good. If you create a pull request I'd be happy to merge.

**Comment by SamVerschueren** [comment]
Is this resolved?

**Comment by ddsol** [comment]
No, it's closed. No one made a pull request and it's been several eons. Also, the `testserver` event is more of a debugging event left in for whoever wants to use it. It leaks some internal unvarnished data which may or may not be useful. But most importantly, it would be a breaking change. For this small fix I don't think it's worth breaking people's code.
