### ISSUE TITLE
Possible to manually make the ping request?

### ISSUE THREAD

**Issue by nathan5x** [ddsol/speedtest.net#16]
Hello,

I'm writing a snippet of code in client (browser) to get the download and upload speed from NodeJS. For now, I'm getting those speeds upon initializing speedtest module in server (Node). However, I'm finding a way to make a request from client to see (log) the speed. Is it possible to manually call / initiate the request? 

Your response would help me a lot. 

Thanks in advance,
Nathan

**Comment by ddsol** [comment]
I'm not sure what you are trying to do. It doesn't run in the browser, but you can start the test at any time you like from node.js.

```
var speedTest=require('speedtest-net');

test=speedTest({maxTime:5000}); // you can call this any time you like and as many times as you like...

test.on('data',function(data){ console.dir(data); }); 

test.on('error',function(err){ console.error(err); });
```

Instead of just logging it to the console, you may want to do something else with it.
