### ISSUE TITLE
Would like your email

### ISSUE THREAD

**Issue by intuitivevoice** [ddsol/speedtest.net#20]
I am interested in discussing some changes to your code to allow this to work with pingtest.net. This would make the data very useful to VoIP implementations. I would willing to pay you for the changes. I can be reached at chris -a-t- intutivetechnology -d-o-t- com

**Comment by ddsol** [comment]
I think that would be a complete rewrite. This code is based on other code I found at the webz. If pingtest.net has not already been dissected then doing so may be a major undertaking involving packet analysis and such and so on and this is very different from some changes to this code. And I don't even have the time to go and figure out if anyone has already done work on it elsewhere in some other language.
