### ISSUE TITLE
`maxTime` does not have any effect

### ISSUE THREAD

**Issue by amilajack** [ddsol/speedtest.net#28]
My mocha tests have a timeout of 10 seconds. My `maxTime` is set to `5000`. If I am not mistaken, this is a bug.

I'm willing to PR to write tests for this project.

**Comment by ddsol** [comment]
PRs are always welcome. You can extend the timeout in mocha. Not sure, but as I recall the timeout is one-way so download+upload can take longer. I also recall it being an estimate and it doesn't chop the download of a block when the timeout is reached. No time to look at it right now...

**Comment by ddsol** [comment]
Download occurs per-block and until the block is finished, the `maxTime` can easily be exceeded. Think of `maxTime` as advisory.
