### ISSUE TITLE
'speed' variable maybe wrong in the documentation

### ISSUE THREAD

**Issue by YuriBrunetto** [ddsol/speedtest.net#32]
Hi, all!

I made a simply CLI for study purposes and I notice something that maybe it's wrong in the documentation. 

## Documentation
```javascript
st.on('downloadspeedprogress', speed => {
  console.log('Download: ' + (speed / 1000).toFixed(2) + ' kB/s')
})
```
dividing the speed by 1000 always outputs a number like `0.01 kB/s`

## What I did
```javascript
st.on('downloadspeedprogress', speed => {
  console.log('Download: ' + (speed * 100).toFixed(2) + ' kB/s')
})
```
so, after some tries I noticed that if I multiply the speed by 100, it outputs the right result, like `999.99 kB/s`

Is this an error or I'm doing something wrong? maybe I didn't understand something there...

**Comment by ddsol** [comment]
Yes, it's actually 125, not 100. The speed is in megabits/s. Multiply by 125 to get the KB/s.
