### ISSUE TITLE
Fix speedtest.js link in package.json

### ISSUE THREAD

**Issue by PavloCherniovyi** [ddsol/speedtest.net#38]
Hello, nice work. I'm using meteor and it displays me an error: 
> Unable to resolve some modules "speedtest.js" in speedtest-net/package.json

That is why this package is not woking after my project deployment to nginx.
Could you please fix this problem (make a file or change a direction) ? It would be really nice. Thank you !

**Comment by ddsol** [comment]
I don't know what the problem is. I can't figure out what the error is saying.

**Comment by zoobibackups** [comment]
> Hello, nice work. I'm using meteor and it displays me an error:
> 
> > Unable to resolve some modules "speedtest.js" in speedtest-net/package.json
> 
> That is why this package is not woking after my project deployment to nginx. Could you please fix this problem (make a file or change a direction) ? It would be really nice. Thank you !

Got the same error on react-native
