### ISSUE TITLE
How to set our own server to conduct speed test?

### ISSUE THREAD

**Issue by jigneshkhatri** [ddsol/speedtest.net#40]
I have my server hosted, which contains large zip file, specially uploaded to conduct speed test. How can I use that file to conduct speed test with this api?

**Comment by ddsol** [comment]
I don't know. This module is designed to work with speedtest.net. I am certain you could Jerry rig it to work with your own server, but the steps involved are too involved and involve recoding code that was coded to work with speedtest.net only. As such it's like writing a new module and even though that can be fun, entertaining and educational, it isn't something I currently have the time, the energy, or the inclination to do.

You could just request that file, time it, and divide the size of the file in bits by the time in seconds and voila, there you have it: bits per second.

**Comment by brettmarl** [comment]
Ookla has a packaged server you can use that is the same protocol. we use this with this library and works great. http://www.speedtest.net/mini.php
