### ISSUE TITLE
[Question] Possible to extract client lib for in-browser

### ISSUE THREAD

**Issue by patcon** [ddsol/speedtest.net#41]
Sorry if this is a silly question, but took a quick look at code and it wasn't immediately obvious to me: with your deep understanding of how speedtest.net works, would be be possible for someone to split this tool into the cli portion and a pure js library that could be run in-browser (ie. no nodejs dep)

**Comment by ddsol** [comment]
I think it would be possible. Maybe not easy, but probably possible.
