### ISSUE TITLE
Can't get library to run test.

### ISSUE THREAD

**Issue by octalmage** [ddsol/speedtest.net#5]
Hola! 

Im having a hard time getting this library to work. This code from the homepage just sits there forever and will never finish:

```
  var speedTest=require('speedtest-net');

  test=speedTest({maxTime:5000});

  test.on('data',function(data){
    console.dir(data);
  });

  test.on('error',function(err){
    console.error(err);
  });
```

And this code: 

```
var speedTest=require('speedtest-net');


speedTest.visual({maxTime:1000,log:true,maxServers:4},function(err,data){
  console.log(data);
});
```

Outputs this: 

```
Testing from 70.112.1.161 at Time Warner Cable, expected dl: 2.59MB/s, expected ul: 0.32MB/s
```

And never finishes. 

Not sure what the issue is. Is there anything I can run to help? I tried logging more events and it gets the full list of servers, but never the best servers. 

Thanks!

**Comment by octalmage** [comment]
Specifying a server works, don't worry about looking into this yet, I should be able to figure it out!

**Comment by ddsol** [comment]
I don't know why it wouldn't do anything. It works for me :). You could try adding lots of console.log's throughout the code (especially pingServers / pingServer /getHttp functions).
I'm closing this for now until there's more info.
