### ISSUE TITLE
speedtest-net no license field

### ISSUE THREAD

**Issue by liuyiji** [ddsol/speedtest.net#58]
npm WARN speedtest-net@1.4.2 No license field.
localhost:speedtest.net-master yiji.liu$ npm install --save speedtest-net
npm ERR! Darwin 17.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "speedtest-net"
npm ERR! node v8.4.0
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install speedtest-net as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yiji.liu/lyj/Demo/speedtest.net-master/npm-debug.log
localhost:speedtest.net-master yiji.liu$

**Comment by ddsol** [comment]
Fixed in 0a60ed1
