### ISSUE TITLE
Add option to bind speedtest to run on specific interface "--source SOURCE"

### ISSUE THREAD

**Issue by rodcul** [ddsol/speedtest.net#61]
where SOURCE = eth0/wlan0/etc. or  IP address

We are contemplating migrating an existing project to nodejs where we'd need to be able to run the speedtest over multiple different interfaces (basically checking speedtest on wlan0 and eth0)

Similar to functionality on https://github.com/sivel/speedtest-cli

It would be preferable to be able to specify interface name (eth0) instead of the IP address (could use something like https://www.npmjs.com/package/network)

```
var speedTest = require('speedtest-net');
var test = speedTest({maxTime: 5000, source: "eth0"});
```

Should include interface in output also `{interface: "eth0"}` or `{interface: "192.168.1.10"}`

All tests should pass.

**Comment by rodcul** [comment]
Posted to Bounty Source - https://www.bountysource.com/issues/61864865-add-option-to-bind-speedtest-to-run-on-specific-interface-source-source

**Comment by DjLegolas** [comment]
It currently works with IP addresses only.
