### ISSUE TITLE
Not working with the React JS

### ISSUE THREAD

**Issue by tis122** [ddsol/speedtest.net#66]
I'm trying to implement the module in React JS. But it not producing the desired results and specifically throwing the error in the console of **" Failed to load http://www.speedtest.net/speedtest-config.php: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. "**

And for more detailed error please check the screenshot.

React JS Env:

  "dependencies": {
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-scripts": "2.0.4",
    "speedtest-net": "^1.4.3"
  }

![speedtestreactissue](https://user-images.githubusercontent.com/29861328/46525204-9da99e00-c8a8-11e8-8f8a-dd3f0c955531.png)

**Comment by ddsol** [comment]
This module isn't designed to work from the browser.
