### ISSUE TITLE
http.get hang without timeout

### ISSUE THREAD

**Issue by fmiceli24** [ddsol/speedtest.net#68]
I know this might be a weird very particular situation but I have encountered that in the following environment (on my electron app) the http.get call never invokes the callback unless I set the timeout option.

- OS: Ubuntu 14.04 (gnome-session-fallback)
- node version: 6.15.1
- electron version: 3.0.0
- speedtest-net version: 1.4.3

It does not even time out, but behaves appropriately. If I do not set that option the http.get function does not invoke the callback nor throws an error.

The fix is to set the option just like below.

```js
options.headers = options.headers || {};
options.headers['user-agent'] = options.headers['user-agent'] || 'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.' + Math.trunc(Math.random() * 400 + 2704) + '.' + Math.trunc(Math.random() * 400 + 103) + ' Safari/537.36';

options.timeout = 20;
  
http.get(options, function(res) {
    if (res.statusCode === 302) {
```

Anyway. Just wanted to leave it somewhere. Any suggestions for the timeout value for the get operations?

**Comment by fmiceli24** [comment]
Anyone?

**Comment by ddsol** [comment]
:+1: A PR could be helpful. I don't have a lot of time for SpeedTest these days. The timeout should be fairly high, maybe `500` or so since they are milliseconds.

**Comment by fmiceli24** [comment]
That is great! I would do a pull request as soon as I learn how to.

Thanks.

**Comment by fmiceli24** [comment]
Created pull request with the change:

https://github.com/ddsol/speedtest.net/pull/69

Let me know if I have to make any changes (this is my first PR!!)

Best,
