### ISSUE TITLE
Licensing and terms of use

### ISSUE THREAD

**Issue by robitacs** [ddsol/speedtest.net#74]
Hoi, do you know if any terms or license apply from Ookla when we use their servers like this in our own applications? It's not mentioned on their website in any way.

**Comment by ddsol** [comment]
Nee. The servers are sponsored by 3rd parties so I doubt Ookla cares. I spoke to  Marc von Holzen who runs the software development team for Ookla. He said there was no problem with the package. Beyond this information you should consult a lawyer, which I am not.
