### ISSUE TITLE
Angular Integration

### ISSUE THREAD

**Issue by HashimJaved09** [ddsol/speedtest.net#76]
Can this plugin be used with angular...???
I have tried to use it but getting these errors: 

ERROR in ./node_modules/speedtest-net/index.js
Module not found: Error: Can't resolve 'crypto' in '/home/hash/speedtest/node_modules/speedtest-net'
ERROR in ./node_modules/speedtest-net/index.js
Module not found: Error: Can't resolve 'http' in '/home/hash/speedtest/node_modules/speedtest-net'
ERROR in ./node_modules/agent-base/patch-core.js
Module not found: Error: Can't resolve 'https' in '/home/hash/speedtest/node_modules/agent-base'
ERROR in ./node_modules/speedtest-net/index.js
Module not found: Error: Can't resolve 'https' in '/home/hash/speedtest/node_modules/speedtest-net'
ERROR in ./node_modules/http-proxy-agent/index.js
Module not found: Error: Can't resolve 'net' in '/home/hash/speedtest/node_modules/http-proxy-agent'
ERROR in ./node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'net' in '/home/hash/speedtest/node_modules/https-proxy-agent'
ERROR in ./node_modules/draftlog/lib/LineCountStream.js
Module not found: Error: Can't resolve 'stream' in '/home/hash/speedtest/node_modules/draftlog/lib'
ERROR in ./node_modules/xml2js/lib/parser.js
Module not found: Error: Can't resolve 'timers' in '/home/hash/speedtest/node_modules/xml2js/lib'
ERROR in ./node_modules/http-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/home/hash/speedtest/node_modules/http-proxy-agent'
ERROR in ./node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/home/hash/speedtest/node_modules/https-proxy-agent'

please is there any other way around to solve this problem and integrate this package with Angular 6...!!!

**Comment by ddsol** [comment]
This is a node.js module and won't work out of the box in the browser.
