### ISSUE TITLE
How to get the result url?

### ISSUE THREAD

**Issue by EnderDev** [ddsol/speedtest.net#78]
https://hasteb.in/ikufunej.js
is my current code, I am wondering how this works, Could not successfully post test results. and it just returns this? What am I doing wrong.

**Comment by ddsol** [comment]
I don't really know. The test result posting has always been flaky I believe. It's not been a priority for the 4 years this module has existed. The actual speedtest results come through other events I think. Read the docs for more info...

**Comment by EnderDev** [comment]
got it working thanks!
