### ISSUE TITLE
Does not work behind proxy

### ISSUE THREAD

**Issue by icyflame** [ddsol/speedtest.net#8]
- Detailed outputs can be found at https://github.com/sindresorhus/is-online/issues/18
- I would be happy to post any more outputs you may need here.
- I used this module through @sindresorhus 's https://github.com/sindresorhus/speed-test/ CLI module.

---

cc @silverwind

**Comment by ddsol** [comment]
The best advice I can give is do not use a proxy. This solution seems to always work for me.

What I really mean to say is that it seems to make little sense to check you internet speed over a proxy... after all, you'll be measuring the lowest common denominator between your internet and the proxy's internet. I don't think speedtest is meant to measure proxy speed.

Closing, but happy to merge in a pull request that allows proxies.

**Comment by kytwb** [comment]
Ok, I'll pull request a proxy support because in the end, it does makes sense to support proxy as well.

**Comment by dthree** [comment]
> The best advice I can give is do not use a proxy. This solution seems to always work for me.

Some people aren't in a position where they can't use a proxy in a given environment.

**Comment by ddsol** [comment]
I would be happy to merge a PR. I don't have the time to add this feature however. That said, reopening this issue may help it get some attention.

**Comment by dthree** [comment]
Thanks. :+1:

**Comment by ddsol** [comment]
Fixed in $47
