### ISSUE TITLE
Final event needed after other events on programmatic (non-visual) test

### ISSUE THREAD

**Issue by jsejcksn** [ddsol/speedtest.net#83]
`speedTest.visual(error, data)` supports a standard callback to continue execution after the test errors or completes, but I don't see this support for running `speedTest`. Am I missing the event that indicates this?

I see `done` (which would work for a success case). I also see `error` (which would work for a failure case), but it can be emitted multiple times. Is there a singular, final event after which the test will stop emitting events?

**Comment by ddsol** [comment]
No, but it'd be easy to make:
```js
var testDone = false;
function callback(err, data) {
  if (testDone) return;
  testDone = true;
  cb(err, data);
}
test.on('done', data => callback(null, data));
test.on('error', err => callback(err));
```
or, using Promises (they are guaranteed to only settle once):
```js
var result = new Promise((resolve, reject) => {
  test.on('done', resolve);
  test.on('error', reject);
});
```
