### ISSUE TITLE
How do i add specific server to test against ?

### ISSUE THREAD

**Issue by rvblerk** [ddsol/speedtest.net#88]
I have this script setup in node-red
but it seems to want to default to overseas servers and not to one locally in my country.

This is what it corrently looks like

![image](https://user-images.githubusercontent.com/43132906/56034388-7932f080-5d27-11e9-9522-5aeba42f004c.png)

and the code
![image](https://user-images.githubusercontent.com/43132906/56034409-85b74900-5d27-11e9-88d6-32f9532bc7a3.png)

**Comment by ddsol** [comment]
The server is picked based on the IP. This is fairly accurate these days, so I'm thinking your originating IP may not be from the country you expect it to be. Note that this module _does not_ determine the IP location, it's speedtest.net that does this and I can't change how they do what they do, so if it's broken I can't fix it.

That said, as the docs clearly state, you can pass a `serverId` in the options. You can get a list of servers [here](https://www.speedtest.net/speedtest-servers-static.php) (also in the docs). This is _not a webpage_, it's an XML document.

The code in the picture you posted doesn't call this module, but just moves some data around. There's nothing in it that can be changed to allow you to specify a server.
