### ISSUE TITLE
The speedtest Node is deleting data from the sequence.

### ISSUE THREAD

**Issue by CyaOnDaNet** [ddsol/speedtest.net#90]
I have data being stored that I need after the node, specifically msg.channel. Using the debug nodes, I see that msg.channel has my data before the node call to speedtest but after it is deleted/removed and the only thing left is msg.payload and msg._msgid

**Comment by ddsol** [comment]
I can't figure out what you mean, and it seems unrelated to SpeedTest.

SpeedTesthas no `msg` or `.payload`, `.channel` or `._msgid`. Also, not sure what you mean by `node` as this can be a number of things, anywhere from a node in a tree data structure, a host or server, a node.js process, etc.

In any case, it's unlikely to be related to speedtest.

**Comment by CyaOnDaNet** [comment]
I apologize, I came here from Node-Red and clicked on the github link provided which was apparently incorrect and sent me to the wrong github page. I found the correct github page now. My bad.
