### ISSUE TITLE
Not suitable for gigabit network. 

### ISSUE THREAD

**Issue by ozanyolyapar** [ddsol/speedtest.net#92]
I ran it multiple times, showed me 1/4 of the current speed (250-290Mbit/s), where I could make over 980Mbit/s using the speedtest.net choosing the same server, as the script does.

**Comment by limpygnome** [comment]
Unfortunately getting similar results.

With node:
  download=56.707 upload=31.828 ping=53.5 server=speedtest.clouvider.co.uk:8080

Actual speed-test.net (292 / 35, ping 21 ms):
https://www.speedtest.net/result/8576277966.png

**Comment by luigimannoni** [comment]
Same here not having a gigabit connection. My top speed is 200mb/s but the package always detects around 70 to 90mb/s

**Comment by ozanyolyapar** [comment]
Meanwhile the project is no longer necessary, as ookla offers its own CLI solution.
https://www.speedtest.net/apps/cli

**Comment by luigimannoni** [comment]
Though I'd still prefer to use a node module rather than installing a third party packages in environments where I do not have a sudo access.

**Comment by ozanyolyapar** [comment]
But as we can see, this package does not meet the requirements. It is not able to provide usable/reliable information about the only use case it is intended for.  Also, I cannot imagine a single case where a speed test should be used in a limited or professional environment. I needed it for my homelab to monitor speed permanently, where a RasPi 4 is more than sufficient and dispensable. So this package is definitely out of question for me. 
Furthermore I am afraid that nodejs causes the bottleneck and it is not in the hands of the developer.

**Comment by ddsol** [comment]
The 2.0.0 version uses the Ookla/speedtest.net CLI directly.
