### ISSUE TITLE
Error bei durchführung unter iobroker per cron

### ISSUE THREAD

**Issue by guergen1** [ddsol/speedtest.net#97]
![grafik](https://user-images.githubusercontent.com/34395245/73595804-c5505b00-451c-11ea-899c-d5bee1a2e532.png)

Eine Neuinstallation via: "npm install --global speed-test" wird ohne Fehler beendet, läuft dennoch nicht.
Node.js v10.18.1
NPM V6.13.7
JS 2.2.8

**Comment by ddsol** [comment]
Please upgrade to the latest version

**Comment by guergen1** [comment]
Habe die 1.6.1 Version schon installiert; allerdings mit dem alten Script... oder muss ich da noch was anpassen?
Der Fehler ist der selbe wie mit der alten Version!

**Comment by ddsol** [comment]
I have no idea what your error is. The errors you're displaying in your issue are not generated by this module.
