### ISSUE TITLE
Not working anymore due to unreachable servers list

### ISSUE THREAD

**Issue by raspyweather** [ddsol/speedtest.net#98]
Currently not working because http://www.speedtest.net/speedtest-servers-static.php seems to be down.
It seems http://c.speedtest.net/speedtest-servers-static.php is the replacement URL.
https://github.com/sivel/speedtest-cli/issues/282

**Comment by raspyweather** [comment]
Might be only me who's affected. Please evaluate. 
This was my temporary fix fyi:
`const test = speedTest({ maxTime: 30000, serversUrl:'http://c.speedtest.net/speedtest-servers-static.php' });`

**Comment by vkentta** [comment]
I can confirm this stopped working in the beginning of this month (February 2020). I have solid logs until that point using https://github.com/vkentta/internet-speed-logger

**Comment by bergerw** [comment]
> Might be only me who's affected. Please evaluate.
> This was my temporary fix fyi:
> `const test = speedTest({ maxTime: 30000, serversUrl:'http://c.speedtest.net/speedtest-servers-static.php' });`

I can confirm that your temporary fix is wokring well. Thanks

**Comment by ddsol** [comment]
Added the new url, package published

**Comment by raspyweather** [comment]
Great job, thanks!

**Comment by bergerw** [comment]
> Added the new url, package published

Thanks a lot. Works perfect now
